

	// ***********************************************************************
	//
	// Collection Class Interface
	//
	// ***********************************************************************
	// Computer Science 102: Data Structures
	// Spring 2014
	// Eric Koskinen
	// New York University
	//
	// (c) Copyright 1995, 2013, Oracle Corporation and/or its affiliates (Oracle).
	// All rights reserved.
	// http://docs.oracle.com/javase/tutorial/information/license.html
	// ***********************************************************************

	// %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	// %%%%% DO NOT EDIT THIS FILE %%%%%
	// %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

	public interface Collection<T> extends Comparable<T> {
	    // Basic operations
	    int size();
	    boolean isEmpty();
	    boolean contains(T element);
	    boolean add(T element);
	    boolean remove(T element);
	    @Override
	    public int compareTo(T o);

	    // Output operations
	    void PrettyPrint();
	}


