

	// ***********************************************************************
	//
	// Set Class Interface
	//
	// ***********************************************************************
	// Computer Science 102: Data Structures
	// Spring 2014
	// Eric Koskinen
	// New York University
	//
	// (c) Copyright 1995, 2013, Oracle Corporation and/or its affiliates (Oracle).
	// All rights reserved.
	// http://docs.oracle.com/javase/tutorial/information/license.html
	// ***********************************************************************

	// %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	// %%%%% DO NOT EDIT THIS FILE %%%%%
	// %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

	public interface Set<T> extends Collection<T> {
	    // Basic operations
	    int size();
	    boolean isEmpty();
	    boolean contains(T element);
	    boolean add(T element);
	    boolean remove(T element);
	 
	    // Output operations
	    void PrettyPrint();
	    String toString();
	}


